# Generated by Django 5.1.6 on 2025-02-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='board',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.AlterField(
            model_name='board',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
